from tkinter import *
from tkinter.ttk import *
from time import strftime
root = Tk()
root.title('Menu')
menubar = Menu(root)
file = Menu(menubar, tearoff =0)
file.add_command(label='New File',command=None)
file.add_command(label='Open..',command=None)
file.add_command(label='Save',command=None)
file.add_separator()
file.add_command(label='Exit',command=root.destroy)
menubar.add_cascade(label='File',menu=file)
root.config(menu=menubar)
edit = Menu(menubar, tearoff=0)
edit.add_command(label='Edit',command=None)
edit.add_command(label='Cut',command=None)
edit.add_command(label='Copy',command=None)
edit.add_command(label='Paste',command=None)
edit.add_command(label='Select',command=None)
edit.add_command(label='Select All',command=None)
edit.add_command(label='Find',command=None)
edit.add_command(label='Find Again',command=None)
edit.add_separator()
edit.add_command(label='Exit',command=root.destroy)
menubar.add_cascade(label='Edit',menu=edit)
root.config(menu=menubar)
help=Menu(menubar, tearoff = 0)
help.add_command(label='TK help',command=None)
help.add_command(label='Help',command=None)
help.add_command(label='Demo',command=None)
help.add_command(label='About TK',command=None)
help.add_separator()
help.add_command(label='Exit',command=root.destroy)
menubar.add_cascade(label='Help',menu=help)
root.config(menu=menubar)
root.mainloop()